version: '3'

# includes:
#   wuwa:
#     taskfile: ./wuwa/taskfile.yml
#     dir: ./wuwa/
#     vars:
#       PUBLISH_SERVER: "bingxl"

tasks:
  build:
    cmd: go build -ldflags="-s -w -H windowsgui" -o ./wwtool.exe .


