// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en":      &dictionary{index: enIndex, data: enData},
		"zh_Hans": &dictionary{index: zh_HansIndex, data: zh_HansData},
	}
	fallback := language.MustParse("zh-Hans")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Advanced":          1,
	"B服官服切换":            48,
	"Cancel":            0,
	"Confirm":           2,
	"Copy":              19,
	"Create Folder":     12,
	"Cut":               18,
	"Enter filename":    6,
	"Error":             14,
	"File":              9,
	"Folder":            10,
	"New Folder":        11,
	"No":                3,
	"OK":                5,
	"Open":              7,
	"Paste":             20,
	"Quit":              15,
	"Redo":              17,
	"Save":              8,
	"Select all":        21,
	"Show Hidden Files": 13,
	"Undo":              16,
	"Yes":               4,
	"下拉框中选择正确的游戏目录后点击启动": 47,
	"主页": 53,
	"之后的切换只需要点击对应的服就可以": 50,
	"切换到 %s 失败, %s":     56,
	"切换到%s":             59,
	"切服结果":              58,
	"则点击`添加游戏目录`后选择游戏目录添加（注: 游戏本体的目录，不是启动器的目录）": 46,
	"删除":   31,
	"别名":   41,
	"取消":   30,
	"启动":   34,
	"启动成功": 35,
	"启动游戏": 44,
	"启动游戏，游戏里打开抽卡记录后点击`获取抽卡链接`， 获取成功后会自动复制到剪切板里": 52,
	"多服": 28,
	"如果游戏不是安装在默认目录上`C:/Program Files/Wuthering Waves/Wuthering Waves Game`": 45,
	"官服/b服切换": 55,
	"已添加":     37,
	"帮助":      54,
	"成功切换到":   57,
	"成功获取到抽卡链接后会自动复制到剪切板": 63,
	"抽卡链接获取": 51,
	"提示":     32,
	"文件":     22,
	"未获取到链接，请先在游戏里打开抽卡记录": 61,
	"查看":           26,
	"添加游戏":         42,
	"添加游戏目录":       43,
	"点击右侧按钮选择游戏目录": 39,
	"点击获取抽卡链接":     60,
	"确认":           29,
	"程序已启动":        36,
	"编辑":           24,
	"请先选择一个目录":     33,
	"目录":           27,
	"退出":           23,
	"选择与操作游戏":      38,
	"选择游戏目录":       40,
	"链接已复制到剪切板":    62,
	"首次运行时点击切换到官服，运行官方启动器，修复游戏；修复完成后点击切换到bilibili服，运行b服启动器，修复游戏": 49,
	"首选项": 25,
}

var enIndex = []uint32{ // 65 elements
	// Entry 0 - 1F
	0x00000000, 0x00000007, 0x00000010, 0x00000018,
	0x0000001b, 0x0000001f, 0x00000022, 0x00000031,
	0x00000036, 0x0000003b, 0x00000040, 0x00000047,
	0x00000052, 0x00000060, 0x00000072, 0x00000078,
	0x0000007d, 0x00000082, 0x00000087, 0x0000008b,
	0x00000090, 0x00000096, 0x000000a1, 0x000000a6,
	0x000000ab, 0x000000b0, 0x000000bc, 0x000000c1,
	0x000000c6, 0x000000d3, 0x000000db, 0x000000e2,
	// Entry 20 - 3F
	0x000000e9, 0x000000ee, 0x00000109, 0x0000010d,
	0x00000119, 0x00000129, 0x00000133, 0x0000014b,
	0x00000176, 0x00000187, 0x0000018d, 0x00000196,
	0x000001a4, 0x000001ad, 0x00000216, 0x0000028b,
	0x000002b1, 0x000002dd, 0x000003c7, 0x0000040f,
	0x0000041e, 0x00000485, 0x0000048a, 0x0000048f,
	0x000004af, 0x000004cd, 0x000004e0, 0x000004ee,
	0x000004fe, 0x00000516, 0x00000555, 0x0000056e,
	// Entry 40 - 5F
	0x000005cc,
} // Size: 284 bytes

const enData string = "" + // Size: 1484 bytes
	"\x02Cancel\x02Advanced\x02Confirm\x02No\x02Yes\x02OK\x02Enter filename" +
	"\x02Open\x02Save\x02File\x02Folder\x02New Folder\x02Create Folder\x02Sho" +
	"w Hidden Files\x02Error\x02Quit\x02Undo\x02Redo\x02Cut\x02Copy\x02Paste" +
	"\x02Select all\x02File\x02Exit\x02Edit\x02Preferences\x02view\x02path" +
	"\x02Multi-server\x02confirm\x02cancel\x02remove\x02info\x02Please select" +
	" a path first\x02run\x02run success\x02Program started\x02has added\x02S" +
	"elect and operate game\x02Click the right button to select game path\x02" +
	"select game path\x02alias\x02add game\x02add game path\x02run game\x02If" +
	" the game is not installed in the default path `C:/Program Files/Wutheri" +
	"ng Waves/Wuthering Waves Game`\x02Then click `Add Game Path` and select " +
	"the game path to add (Note: the path to the game executable, not the lau" +
	"ncher)\x02select target game and then click run\x02change server between" +
	" bilibili and official\x02When running for the first time, click to swit" +
	"ch to the official server, run the official launcher to repair the game;" +
	" after the repair is complete, click to switch to the Bilibili server, r" +
	"un the Bilibili launcher to repair the game\x02Subsequent switching only" +
	" requires clicking on the corresponding server\x02get gacha link\x02open" +
	" gacha history in game, and then click 'get gacha link', will set clipbo" +
	"ard automated when success\x02Home\x02help\x02official/bilibili server c" +
	"hange\x02failed change to %[1]s, %[2]s\x02success changed to\x02change r" +
	"esult\x02change to %[1]s\x02Click to get gacha link\x02Link not obtained" +
	", please open gacha history in the game first\x02Link copied to clipboar" +
	"d\x02After successfully obtaining the gacha link, it will be automatical" +
	"ly copied to the clipboard"

var zh_HansIndex = []uint32{ // 65 elements
	// Entry 0 - 1F
	0x00000000, 0x00000007, 0x00000010, 0x00000018,
	0x0000001b, 0x0000001f, 0x00000022, 0x00000031,
	0x00000036, 0x0000003b, 0x00000040, 0x00000047,
	0x00000052, 0x00000060, 0x00000072, 0x00000078,
	0x0000007d, 0x00000082, 0x00000087, 0x0000008b,
	0x00000090, 0x00000096, 0x000000a1, 0x000000a8,
	0x000000af, 0x000000b6, 0x000000c0, 0x000000c7,
	0x000000ce, 0x000000d5, 0x000000dc, 0x000000e3,
	// Entry 20 - 3F
	0x000000ea, 0x000000f1, 0x0000010a, 0x00000111,
	0x0000011e, 0x0000012e, 0x00000138, 0x0000014e,
	0x00000173, 0x00000186, 0x0000018d, 0x0000019a,
	0x000001ad, 0x000001ba, 0x0000021c, 0x00000290,
	0x000002c7, 0x000002d8, 0x00000375, 0x000003a9,
	0x000003bc, 0x00000435, 0x0000043c, 0x00000443,
	0x00000455, 0x00000473, 0x00000483, 0x00000490,
	0x0000049f, 0x000004b8, 0x000004f2, 0x0000050e,
	// Entry 40 - 5F
	0x00000548,
} // Size: 284 bytes

const zh_HansData string = "" + // Size: 1352 bytes
	"\x02Cancel\x02Advanced\x02Confirm\x02No\x02Yes\x02OK\x02Enter filename" +
	"\x02Open\x02Save\x02File\x02Folder\x02New Folder\x02Create Folder\x02Sho" +
	"w Hidden Files\x02Error\x02Quit\x02Undo\x02Redo\x02Cut\x02Copy\x02Paste" +
	"\x02Select all\x02文件\x02退出\x02编辑\x02首选项\x02查看\x02目录\x02多服\x02确认\x02取消" +
	"\x02删除\x02提示\x02请先选择一个目录\x02启动\x02启动成功\x02程序已启动\x02已添加\x02选择与操作游戏\x02点击右" +
	"侧按钮选择游戏目录\x02选择游戏目录\x02别名\x02添加游戏\x02添加游戏目录\x02启动游戏\x02如果游戏不是安装在默认目录上`" +
	"C:/Program Files/Wuthering Waves/Wuthering Waves Game`\x02则点击`添加游戏目录`后选择" +
	"游戏目录添加（注: 游戏本体的目录，不是启动器的目录）\x02下拉框中选择正确的游戏目录后点击启动\x02B服官服切换\x02首次运行时点击" +
	"切换到官服，运行官方启动器，修复游戏；修复完成后点击切换到bilibili服，运行b服启动器，修复游戏\x02之后的切换只需要点击对应的服就" +
	"可以\x02抽卡链接获取\x02启动游戏，游戏里打开抽卡记录后点击`获取抽卡链接`， 获取成功后会自动复制到剪切板里\x02主页\x02帮助" +
	"\x02官服/b服切换\x02切换到 %[1]s 失败, %[2]s\x02成功切换到\x02切服结果\x02切换到%[1]s\x02点击获取抽" +
	"卡链接\x02未获取到链接，请先在游戏里打开抽卡记录\x02链接已复制到剪切板\x02成功获取到抽卡链接后会自动复制到剪切板"

	// Total table size 3404 bytes (3KiB); checksum: 473BE42
