name: Build Windows Fyne app with UPX and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APPNAME: wwtool.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Install UPX
      run: choco install upx -y

    - name: Install Fyne CLI
      run: go install fyne.io/tools/cmd/fyne@latest

    # - name: Add Go bin to PATH
    #   shell: pwsh
    #   run: |
    #     $env:GOPATH = $(go env GOPATH)
    #     echo "$env:GOPATH\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build Windows executable with Fyne
      run: fyne package --os windows --arch amd64 -name $APPNAME

    - name: Compress executable with UPX
      run: upx --best --lzma $APPNAME

    - name: Create GitHub Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        files: $APPNAME
