name: Build Windows Fyne app with UPX and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      APPNAME: wwtool.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Cache Go modules and Fyne CLI
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install UPX
      run: choco install upx -y

    - name: Install Fyne CLI
      run: go install fyne.io/tools/cmd/fyne@latest

    - name: Build Windows executable with Fyne
      run: fyne package -os windows -icon Icon.ico -name $APPNAME

    - name: Compress executable with UPX
      run: upx --best --lzma $APPNAME

    - name: Create GitHub Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        files: $APPNAME
